config/routes.rb
Rails.application.routes.draw do
  root :to => 'favorite_sites#index'

  resources :favorite_sites do
    collection do
      post 'search'
      get 'search'
    end
  end

  namespace :admin do
    resources :users
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/user.rb
class Admin::User < ActiveRecord::Base
  validates_uniqueness_of :name
end

app/models/favorite_site.rb
class FavoriteSite < ActiveRecord::Base
  belongs_to :admin_user, class_name: 'Admin::User'

  STAR = {one: 1, two: 2, three: 3, four: 4 ,five: 5}

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:name, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorite_sites_controller.rb
class FavoriteSitesController < ApplicationController
  before_action :set_favorite_site, only: [:show, :edit, :update, :destroy]

  # GET /favorite_sites
  # GET /favorite_sites.json
  def index
    @favorite_sites = FavoriteSite.page(params[:page])
    @favorite_form = FavoriteSite::SearchForm.new
  end

  # GET /favorite_sites/1
  # GET /favorite_sites/1.json
  def show
  end

  # GET /favorite_sites/new
  def new
    @favorite_site = FavoriteSite.new
    @favorite_edit_form = FavoriteSite::EditForm.new
    # @favorite_edit_form = FavoriteSite::EditForm.new
  end

  # GET /favorite_sites/1/edit
  def edit
    @favorite_edit_form = FavoriteSite::EditForm.new
    @favorite_edit_form.favorite_site = FavoriteSite.find(params[:id])
  end

  # POST /favorite_sites
  # POST /favorite_sites.json
  def create
    @favorite_edit_form = FavoriteSite::EditForm.new(favorite_site_params)
    @favorite_form = FavoriteSite::SearchForm.new

    respond_to do |format|
      if @favorite_edit_form.save
        format.html { redirect_to favorite_sites_path }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /favorite_sites/1
  # PATCH/PUT /favorite_sites/1.json
  def update
    @favorite_edit_form = FavoriteSite::EditForm.new(favorite_site_params)
    @favorite_edit_form.id = params[:id]
    respond_to do |format|
      if @favorite_edit_form.save
        @favorite_form = FavoriteSite::SearchForm.new
        format.html { redirect_to favorite_sites_path, notice: '更新しました'}
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /favorite_sites/1
  # DELETE /favorite_sites/1.json
  def destroy
    @favorite_site.destroy
    respond_to do |format|
      format.html { redirect_to favorite_sites_url, notice: 'Favorite site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @favorite_form = FavoriteSite::SearchForm.new(params[:favorite_site_search_form])
    @favorite_sites = @favorite_form.search.page(params[:page])

    render 'index'
    # render 'index', :formats => [:json], :handlers => [:jbuilder]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_site
      @favorite_site = FavoriteSite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_site_params
      # params[:favorite_site]
      params.require(:favorite_site_edit_form).permit(:admin_user, :url, :rate)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_sites_helper.rb
module FavoriteSitesHelper
  def rate_image(rate)
    image_name = ""
    case rate
    when 1 then
      image_name = "rate1.png"
	when 2 then
	  image_name = "rate2.png"
	when 3 then
	  image_name = "rate3.png"
	when 4 then
	  image_name = "rate4.png"
	when 5 then
	  image_name = "rate4.png"
  	end

  	image_name
  end

  def search_rate_select_values
  	{
  	  '星1つ以上' => FavoriteSite::STAR[:one],
  	  '星2つ以上' => FavoriteSite::STAR[:two],
  	  '星3つ以上' => FavoriteSite::STAR[:three],
  	  '星4つ以上' => FavoriteSite::STAR[:four],
  	  '星5つ以上' => FavoriteSite::STAR[:five]
  	}
  end
end

app/views/admin/users/_form.html.erb
<%= form_for @admin_user, :html => { :class => "form-horizontal user" } do |f| %>

    <% if @admin_user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@admin_user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @admin_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@admin_user[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@admin_user[:email]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            admin_users_path, :class => 'btn btn-default' %>

<% end %>

app/views/admin/users/edit.html.erb
<%- model_class = Admin::User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/users/index.html.erb
<%- model_class = Admin::User -%>
<div class="page-header">
  <h1><%= 'ユーザー一覧'%></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @admin_users.each do |user| %>
      <tr>
        <td><%= link_to user.id, admin_user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to '編集', edit_admin_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '削除しますか?' }, :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新規作成', new_admin_user_path, :class => 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<%- model_class = Admin::User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/users/show.html.erb
<%- model_class = Admin::User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @admin_user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @admin_user.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_user_path(@admin_user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_user_path(@admin_user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/favorite_sites/_form.html.erb
<%= form_for(@favorite_site) do |f| %>
  <% if @favorite_site.errors.any? %>
    <div id="error_explanation">
      <% @favorite_site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="panel-body">
      <%= form_for @favorite_edit_form, url: polymorphic_path(@favorite_edit_form.favorite_site), method: (@favorite_edit_form.favorite_site.persisted?  ? :patch : :post), html: { class: 'form-horizontal'} do |f| %>
        <div class="form-group">
          <%= f.label :admin_user, "ユーザー名:", class: 'control-label col-lg-3'  %>
          <%= f.collection_select :admin_user, Admin::User.all, :id, :name, {include_blank: false }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :url, "URL:", class: 'control-label col-lg-3'  %>
          <%= f.text_field :url, class: 'form-control', placeholder:'http://~' %>
        </div>

        <div class="form-group">
          <div class="col-lg-9">
            <%= f.label :rate, "評価:", class: 'control-label'  %>
          </div>
          <% FavoriteSite::STAR.each {|key, value| %>
          <div class="col-lg-9">
            <label class="radio-inline">
              <%= f.radio_button :rate, value %>
              <% image = rate_image(value) %>
              <%= image_tag(image, :size => "115x25", :alt => key) if image.present? %>
            </label>
          </div>
          <% } %>
        </div>

        <div class="form-group">
        <% if controller.action_name == 'edit' %>
          <div class="control-label">
            <%= f.submit "更新する", class: "btn btn-primary col-lg-1 col-lg-offset-1" %>
          </div>
        <% else %>
          <div class="control-label">
            <%= f.submit "新規登録", class: "btn btn-primary col-lg-1 col-lg-offset-1" %>
          </div>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/favorite_sites/edit.html.erb
<h1>お気に入りサイト 編集</h1>

<%= render 'form' %>

<%= link_to 'Back', favorite_sites_path %>

app/views/favorite_sites/index.html.erb
<h1>お気に入りサイト一覧</h1>

<div class="row">
  <%= button_to '新規作成', new_favorite_site_path, :method => :get, id: 'create_btn',:class => 'btn btn-primary col-lg-1 col-md-offset-9' %>
</div>
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= form_for @favorite_form, url: :search_favorite_sites, html: { class: 'form-horizontal'} do |f| %>
        <fieldset>
          <legend>絞り込み条件</legend>
          <div class="form-group">
            <%= f.label :name, "ユーザー名:", class: 'control-label col-lg-3' %>
            <div class="col-lg-6">
              <%= f.collection_select :user, Admin::User.all, :id, :name, {include_blank: false }, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :url, "URL:", class: 'control-label col-lg-3' %>
            <div class="col-lg-6">     
              <%= f.text_field :url, class: 'form-control', placeholder:'http://~' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :rate, "評価:", class: 'control-label col-lg-3' %>
            <div class="col-sm-4">
              <%= f.select :rate, search_rate_select_values, { include_blank: false }, { id: 'rate-select', class: 'form-control' }  %>
            </div>
          </div>

          <button type="submit" class="btn btn-primary col-sm-1 col-md-offset-8">検索</button>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

<div class"row">
  <div class="col-lg-offset-1 col-lg-10">
    <% if @favorite_sites.present? %>
      <%= paginate @favorite_sites %>
      <%= page_entries_info(@favorite_sites) %>
      <table class="table">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>URL</th>
            <th>評価</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @favorite_sites.each do |favorite_site| %>
            <tr>
              <td><%= favorite_site.try(:admin_user).try(:name) %></td>
              <td><%= link_to favorite_site.url, favorite_site.url %></td>
              <% image = rate_image(favorite_site.rate) %>
              <td><%= image_tag(image, :size => "115x25", :alt => favorite_site.rate) if image.present? %></td>
              <td><%= link_to '編集', edit_favorite_site_path(favorite_site) %></td>
              <td><%= link_to '削除', favorite_site, method: :delete, data: { confirm: '削除しますか?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/favorite_sites/new.html.erb
<h1>お気に入りサイト 新規登録</h1>

<%= render 'form' %>

<%= link_to 'Back', favorite_sites_path %>

app/views/favorite_sites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_favorite_site_path(@favorite_site) %> |
<%= link_to 'Back', favorite_sites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shaun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>